Add type equivalence test.
- If you set Embed Interop Types to true then you get

```
Error CS1759: Cannot embed interop types from assembly 'Moq.Com.Demo\packages\Microsoft.VisualStudio.OLE.Interop.7.10.6071\lib\Microsoft.VisualStudio.OLE.Interop.dll' #because it is missing either the 'ImportedFromTypeLibAttribute' attribute or the 'PrimaryInteropAssemblyAttribute' attribute
```